command_timeout = 5000
scan_timeout = 500
add_newline = true
# format = "$status$directory$git_branch$conda$time$username$hostname\n$status$character"

[python]
disabled = true

[rlang]
disabled = true

[git_status]
disabled = true

[status]
disabled = false
format = "[$common_meaning $status]($style) "


# sometimes using unicode chars here seems to break vscode rendering?
# [character]
# success_symbol = '[>](green)'
# error_symbol = '[>](red)'