command_timeout = 5000
scan_timeout = 500
add_newline = true
# format = "$status$directory$git_branch$conda$time$username$hostname\n$status$character"

[python]
disabled = false

[git_status]
disabled = true


[status]
disabled = false
format="[$symbol $status]($style) "
